name: "test, lint and publish"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "Test (${{ matrix.python-version }}"
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12"]
    uses: ./.github/workflows/_test.yaml
    with:
      coverage: true
      python-version: ${{ matrix.python-version }}
  lint:
    name: "Lint (${{ matrix.python-version }}"
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12"]
    needs: test
    uses: ./.github/workflows/_lint.yaml
    with:
      python-version: ${{ matrix.python-version }}